"""
Update the status of a tracked posting -- the record of what you've actually
applied to.

Usage:
    python mark.py --list                                     # show everything not still "new"
    python mark.py --list --status applied
    python mark.py 8094078 --status applied --date 2026-08-09
    python mark.py 8094078 --status rejected --date 2026-08-12 --note "no sponsorship"
    python mark.py --url "https://careers.toasttab.com/jobs?gh_jid=8094078" --status applied --date 2026-08-09

The positional argument is any substring of the posting's URL -- the
Greenhouse/Ashby job id (e.g. 8094078) is the convenient one to paste from
the shortlist. The match must be unique, otherwise nothing is written and
the candidates are printed; pass --all to deliberately mark every match
(useful for skipping a whole batch of duplicate Toast city postings).

Writes to data/jobs.csv, the source of truth. data/shortlist.csv is a
derived view and gets regenerated by shortlist.py, so marking there would
be silently thrown away.
"""

import argparse
import csv
import os
import sys

from fetch_jobs import date_kind_for

DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
CSV_PATHS = {
    "us": os.path.join(DATA_DIR, "jobs.csv"),
    "french": os.path.join(DATA_DIR, "jobs_french.csv"),
}

# Ordered roughly by pipeline progression. PENDING statuses still need action
# from you, so shortlist.py keeps showing them; DONE statuses are hidden
# there by default.
PENDING_STATUSES = ["new", "interested", "drafted"]
DONE_STATUSES = ["applied", "interviewing", "offer", "rejected", "skipped"]
STATUSES = PENDING_STATUSES + DONE_STATUSES

FIELDS = ["company", "title", "location", "url", "sponsors_h1b",
          "years_experience", "updated_at", "date_kind", "status",
          "first_seen", "status_updated", "note"]


def load(csv_path):
    if not os.path.exists(csv_path):
        sys.exit(f"No tracked jobs at {csv_path} -- run tracker.py first.")
    with open(csv_path, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    # status_updated/note/date_kind postdate the original tracker schema. Filled
    # in on load so save() can't blank out a column this script never touches.
    for row in rows:
        row.setdefault("status_updated", "")
        row.setdefault("note", "")
        if not row.get("date_kind"):
            row["date_kind"] = date_kind_for(row["company"], row["url"])
    return rows


def save(csv_path, rows):
    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDS)
        writer.writeheader()
        writer.writerows(rows)


def show(row):
    status = row["status"] + (f" ({row['status_updated']})"
                              if row["status_updated"] else "")
    line = (f"{status:<24} {row['company']:<14} {row['title'][:40]:<40} "
            f"{row['location'][:22]:<22} {row['url']}")
    return line + (f"\n{'':<24} note: {row['note']}" if row["note"] else "")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("match", nargs="?",
                        help="substring of the posting URL (the job id works)")
    parser.add_argument("--url", help="same as the positional argument, spelled out")
    parser.add_argument("--status", choices=STATUSES)
    parser.add_argument("--date", help="date of this status change, YYYY-MM-DD "
                                       "(script cannot read the clock itself)")
    parser.add_argument("--note", default=None, help="free-text note on this row")
    parser.add_argument("--list", action="store_true",
                        help="list tracked rows instead of updating one")
    parser.add_argument("--all", action="store_true",
                        help="allow updating every row matching --match, not just a unique one")
    parser.add_argument("--french", action="store_true",
                        help="operate on data/jobs_french.csv instead")
    args = parser.parse_args()

    csv_path = CSV_PATHS["french" if args.french else "us"]
    rows = load(csv_path)

    if args.list:
        # With --status, list exactly that status; otherwise show everything
        # you've touched, which is the "what have I actually done" view.
        if args.status:
            selected = [r for r in rows if r["status"] == args.status]
        else:
            selected = [r for r in rows if r["status"] != "new"]
        selected.sort(key=lambda r: (r["status_updated"], r["company"]))
        for r in selected:
            print(show(r))
        counts = {}
        for r in rows:
            counts[r["status"]] = counts.get(r["status"], 0) + 1
        print(f"\n{len(selected)} shown. Totals: "
              + "  ".join(f"{s}:{counts[s]}" for s in STATUSES if counts.get(s)))
        return

    needle = args.match or args.url
    if not needle or not args.status:
        sys.exit("Need a URL substring and --status (or use --list). "
                 "See --help.")
    if not args.date:
        sys.exit("Need --date YYYY-MM-DD so the status change is dated.")

    matches = [r for r in rows if needle in r["url"]]
    if not matches:
        sys.exit(f"No tracked posting matching {needle!r}.")
    if len(matches) > 1 and not args.all:
        print(f"{needle!r} matches {len(matches)} postings -- narrow it down, "
              f"or pass --all to mark them all:\n", file=sys.stderr)
        for r in matches:
            print("  " + show(r), file=sys.stderr)
        sys.exit(1)

    for r in matches:
        previous = r["status"]
        r["status"] = args.status
        r["status_updated"] = args.date
        if args.note is not None:
            r["note"] = args.note
        print(f"{previous} -> {args.status}: {r['company']} / {r['title']}")

    save(csv_path, rows)
    print(f"\nUpdated {len(matches)} row(s) in {csv_path}.")


if __name__ == "__main__":
    main()
